name: 14 - Working with Artifacts
on: workflow_dispatch
env:
  build-artifact-key: app-${{ github.sha }}
  test-coverage-key: test-coverage-${{ github.sha }}
jobs:
  test-build:
    defaults:
      run:
        working-directory: ./14-artifacts/react-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v3
        with:
          key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
          path: 14-artifacts/react-app/node_modules
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Unit tests
        run: npm run test -- --coverage
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.test-coverage-key }}
          path: 14-artifacts/react-app/coverage
      - name: Build code
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.build-artifact-key }}
          path: 14-artifacts/react-app/build
  deploy:
    needs: test-build
    runs-on: ubuntu-latest
    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.build-artifact-key }}
          path: build
      - name: Show folder structure
        run: ls -R